# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Canonical Ltd.

name: Smoke
run-name: Smoke test with snapd from channel ${{ inputs.snapd-snap-channel }} or revision ${{ inputs.snapd-snap-revision }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    inputs:
      snapd-snap-revision:
        description: "Specific revision of snapd to use (0 uses channel)"
        type: number
        default: 0
      snapd-snap-channel:
        description: "Specific channel of snapd to use"
        type: choice
        options:
          - latest/stable
          - latest/candidate
          - latest/beta
          - latest/edge
        default: latest/stable

jobs:
  ubuntu:
    name: "Ubuntu ${{ matrix.version-id }}"
    strategy:
      matrix:
        lts: [false]
        wsl-enable-systemd: [false]
        include:
          # - codename: jammy
          #   version-id: "22.04"
          #   wsl-enable-systemd: true
          - codename: noble
            version-id: "24.04"
    uses: ./.github/workflows/generic.yaml
    with:
      distro-name: Ubuntu ${{ matrix.version-id }}
      wsl-rootfs-url: https://cloud-images.ubuntu.com/wsl/${{ matrix.codename }}/current/ubuntu-${{ matrix.codename }}-wsl-amd64-ubuntu.rootfs.tar.gz
      wsl-rootfs-file: ubuntu-${{ matrix.codename }}-wsl-amd64-wsl.rootfs.tar.gz
      wsl-distro-name: Test-Ubuntu-${{ matrix.version-id }}
      wsl-enable-systemd: ${{ matrix.wsl-enable-systemd }}
      snapd-snap-revision: ${{ github.event.inputs.snapd-snap-revision != 0 && fromJSON(github.event.inputs.snapd-snap-revision) || 0 }}
      snapd-snap-channel: ${{ github.event.inputs.snapd-snap-channel != '' && github.event.inputs.snapd-snap-channel || 'latest/stable' }}
